## 시니어

- DQN 코드 작성 (전에 성능 나왔으면, DDQN 구현)  
- 먼저 (5,5)와 같이 작은 사이즈의 환경에서 시작  
- 매직넘버 사용 지양  



---  


### 1. **작은 사이즈, 적은 지뢰 밀도** 환경에서 학습되는지 확인  

### 시니어용 세팅

In [1]:
! git clone "https://github.com/KanghwaSisters/DQN_minesweeper.git"

Cloning into 'DQN_minesweeper'...
remote: Enumerating objects: 9824, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 9824 (delta 8), reused 0 (delta 0), pack-reused 9809 (from 1)
Receiving objects: 100% (9824/9824), 69.07 MiB | 9.40 MiB/s, done.
Resolving deltas: 100% (2658/2658), done.
Updating files: 100% (173/173), done.


In [2]:
import os
os.chdir('/content/DQN_minesweeper/codes/Environment')

In [3]:
! python reward5.py
from reward5 import *

In [4]:
env = MinesweeperEnv(map_size=(5,5),
                     n_mines=5,
                     rewards={'win':1, 'lose':-1, 'progress':0.3, 'guess':0.3, 'no_progress' : -1},
                     dones={'win':True, 'lose':True, 'progress':False, 'guess':False, 'no_progress' : False},
                     dim2=False)

In [5]:
env.state

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]

In [6]:
env.seed_mines()

array([[0, 'M', 0, 0, 0],
       [0, 'M', 0, 0, 'M'],
       [0, 0, 'M', 0, 0],
       [0, 'M', 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=object)

In [ ]:
env.board

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 'M', 3, 1, 0],
        [2, 'M', 'M', 1, 0],
        [2, 3, 2, 1, 0],
        ['M', 2, 0, 0, 0],
        ['M', 2, 0, 0, 0]]], dtype=object)

In [ ]:
env.step(4)

(array([[[0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1.],
         [0., 0., 1., 1., 1.],
         [0., 0., 1., 1., 1.]],
 
        [[0., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0.,

In [ ]:
env.step(1)

(array([[[0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1.],
         [0., 0., 1., 1., 1.],
         [0., 0., 1., 1., 1.]],
 
        [[0., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0.,

In [ ]:
env.reset()

In [ ]:
env.state

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]

### NN

In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [8]:
class NeuralNet(nn.Module):

    def __init__(self, output):

        super(NeuralNet, self).__init__()

        self.drop_prob = 0.25

        self.conv1 = nn.Conv2d(11, 64, kernel_size = 3, stride = 1, padding = 1)
        self.batchnorm1 = nn.BatchNorm2d(64)
        self.conv2 = nn.Conv2d(64, 64, kernel_size = 3, stride = 1, padding = 1)
        self.batchnorm2 = nn.BatchNorm2d(64)
        self.conv3 = nn.Conv2d(64, 64, kernel_size = 3, stride = 1, padding = 1)
        self.batchnorm3 = nn.BatchNorm2d(64)
        self.dropout = nn.Dropout(p = self.drop_prob)
        self.fc1 = nn.Linear(64*5*5, 128)
        self.fc2 = nn.Linear(128, output)

    def forward(self, x):


        x = self.conv1(x)
        x = F.relu(self.batchnorm1(x))
        x = self.dropout(x)

        x = self.conv2(x)
        x = F.relu(self.batchnorm2(x))

        x = self.conv3(x)
        x = F.relu(self.batchnorm3(x))
        x = self.dropout(x)

        x = x.view(-1, 64*5*5)
        x = self.fc1(x)
        x = self.fc2(x)
        return x

### Agent

In [9]:
import random
import numpy as np
import pandas as pd
from collections import deque
import matplotlib.pyplot as plt
import copy

import torch
import torch.optim as optim
from torch.optim import lr_scheduler
import torch.nn as nn
import torch.nn.functional as F

In [16]:
BATCH_SIZE = 64
MEMORY_SIZE = 2000
MEMORY_SIZE_MIN = 100

EPSILON = 0.99
EPSILON_DECAY = 0.999
EPSILON_MIN = 0.01
DISCOUNT_FACTOR = 0.1

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

LEARNING_RATE = 0.001
LEARNING_RATE_DECAY = 0.99975
LEARN_EPOCH = 500

UPDATE_TIME = 5

## DQN

In [11]:
class Agent:

    def __init__(self, action_size):

        self.action_size = action_size

        self.batch_size = BATCH_SIZE
        self.memory_size = MEMORY_SIZE
        self.memory_size_min = MEMORY_SIZE_MIN
        self.memory = deque(maxlen = self.memory_size)

        self.epsilon = EPSILON
        self.epsilon_decay = EPSILON_DECAY
        self.epsilon_min = EPSILON_MIN
        self.discount_factor = DISCOUNT_FACTOR

        self.device = DEVICE

        self.learning_rate = LEARNING_RATE
        self.learning_rate_decay = LEARNING_RATE_DECAY
        self.learn_epoch = LEARN_EPOCH
        self.loss = nn.MSELoss()
        self.loss_list = []
        self.model = NeuralNet(self.action_size).to(self.device)
        self.target_model = NeuralNet(self.action_size).to(self.device)
        self.optimizer = optim.Adam(self.model.parameters(), lr = self.learning_rate, eps = 1e-4)
        self.lr_scheduler = lr_scheduler.CyclicLR(self.optimizer, base_lr=0.00005,
                                              step_size_up=5, max_lr=0.01,
                                              gamma=0.5, mode='exp_range')

        self.update_time = UPDATE_TIME
        self.update_target_model()

    def update_target_model(self):
        self.target_model.load_state_dict(self.model.state_dict())

    def get_action(self, state):
        random_prob = np.random.rand()
        if random_prob <= self.epsilon:
            action_idx = np.random.choice(range(self.action_size))
        else:
            self.model.eval()

            with torch.no_grad():
                state = torch.tensor(state, dtype=torch.float32).to(self.device).unsqueeze(0) ##
                q_value = self.model(state)
                _, action_idx = torch.max(q_value, dim=1)
                action_idx = action_idx.item()

        return action_idx

    def append_sample(self, state, action, next_state, reward, done):
        self.memory.append((state, action, next_state, reward, done))

    def train_model(self):

        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

        mini_batch = random.sample(self.memory, self.batch_size)
        states, actions, next_states, rewards, dones = zip(*mini_batch)

        states = torch.tensor(states, dtype = torch.float32).to(self.device)#
        actions = torch.tensor(actions, dtype = torch.int64).to(self.device)
        next_states = torch.tensor(next_states, dtype = torch.float32).to(self.device)#
        rewards = torch.tensor(rewards, dtype = torch.float32).to(self.device).reshape(-1, 1)
        dones = torch.tensor(dones, dtype = torch.int64).to(self.device).reshape(-1, 1)


        self.model.train()
        self.target_model.eval()

        predicts = self.model(states)

        with torch.no_grad():

            target_predict, _ = torch.max(self.target_model(next_states), dim = 1)
            target_pred = target_predict.reshape(-1, 1)

        targets = rewards + (1 - dones) * self.discount_factor * target_pred
        targets = targets.flatten()

        target_q_values = copy.deepcopy(predicts.detach())
        target_q_values[range(BATCH_SIZE), actions] = targets

        loss = self.loss(predicts, target_q_values)
        self.loss_list.append(loss.item())

        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()


## DDQN

In [17]:
class Agent:

    def __init__(self, action_size):

        self.action_size = action_size

        self.batch_size = BATCH_SIZE
        self.memory_size = MEMORY_SIZE
        self.memory_size_min = MEMORY_SIZE_MIN
        self.memory = deque(maxlen = self.memory_size)

        self.epsilon = EPSILON
        self.epsilon_decay = EPSILON_DECAY
        self.epsilon_min = EPSILON_MIN
        self.discount_factor = DISCOUNT_FACTOR

        self.device = DEVICE

        self.learning_rate = LEARNING_RATE
        self.learning_rate_decay = LEARNING_RATE_DECAY
        self.learn_epoch = LEARN_EPOCH
        self.loss = nn.MSELoss()
        self.loss_list = []
        self.model = NeuralNet(self.action_size).to(self.device)
        self.target_model = NeuralNet(self.action_size).to(self.device)
        self.optimizer = optim.Adam(self.model.parameters(), lr = self.learning_rate, eps = 1e-4)
        self.lr_scheduler = lr_scheduler.CyclicLR(self.optimizer, base_lr=0.00005,
                                              step_size_up=5, max_lr=0.01,
                                              gamma=0.5, mode='exp_range')

        self.update_time = UPDATE_TIME
        self.update_target_model()

    def update_target_model(self):
        self.target_model.load_state_dict(self.model.state_dict())

    def get_action(self, state):
        random_prob = np.random.rand()
        if random_prob <= self.epsilon:
            action_idx = np.random.choice(range(self.action_size))
        else:
            self.model.eval()

            with torch.no_grad():
                state = torch.tensor(state, dtype=torch.float32).to(self.device).unsqueeze(0) ##
                q_value = self.model(state)
                _, action_idx = torch.max(q_value, dim=1)
                action_idx = action_idx.item()

        return action_idx

    def append_sample(self, state, action, next_state, reward, done):
        # done: 게임이 끝났으면 True
        # 이때 reward를 다르게 줌
        self.memory.append((state, action, next_state, reward, done))

    def train_model(self):

        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

        mini_batch = random.sample(self.memory, self.batch_size)
        states, actions, next_states, rewards, dones = zip(*mini_batch)

        states = torch.tensor(states, dtype = torch.float32).to(self.device)#
        actions = torch.tensor(actions, dtype = torch.int64).to(self.device)
        next_states = torch.tensor(next_states, dtype = torch.float32).to(self.device)#
        rewards = torch.tensor(rewards, dtype = torch.float32).to(self.device).reshape(-1, 1)
        dones = torch.tensor(dones, dtype = torch.int64).to(self.device).reshape(-1, 1)


        self.model.train()
        self.target_model.eval()

        # 현재 상태에 대한 action별 큐함수(인공신경망의 예측)
        predicts = self.model(states)

        with torch.no_grad():
        # DDQN: 현재 모델로 다음 상태에서 최대 Q-value의 행동 선택
          next_action_indices = torch.argmax(self.model(next_states), dim=1).unsqueeze(1)

          # 타깃 모델을 사용해 다음 상태에서 선택한 행동에 대한 Q-value 추출
          target_q_values = self.target_model(next_states).gather(1, next_action_indices)

          # 벨만 최적 방정식으로 타겟 Q-value 계산
          targets = rewards + (1 - dones) * self.discount_factor * target_q_values

        # 선택한 행동에 대한 Q-value만 업데이트
        target_q_values = copy.deepcopy(predicts.detach())
        target_q_values[range(self.batch_size), actions] = targets.flatten()

        # 손실 계산
        loss = self.loss(predicts, target_q_values)
        self.loss_list.append(loss.item())

        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()


## DQN Main

In [29]:

env = MinesweeperEnv(map_size=(5,5),
                     n_mines=5,
                     rewards={'win': 1, 'lose': -1, 'progress': 0.3, 'guess': 0.3, 'no_progress': -1},
                     dones={'win': True, 'lose': True, 'progress': False, 'guess': False, 'no_progress': False},
                     dim2=False)

# 에이전트 초기화
agent = Agent(action_size=25)

# 학습 설정
EPISODES = 2000
episodes, scores, score_avg, total_action, length_memory, win_list = [], [], [], [], [], []

for epi in range(EPISODES):
    done = False
    score = 0
    total_action_epi = []

    # 게임 초기화
    env.reset()
    state = env.state

    while not done:
        # 현재 상태에 대한 행동 선택
        action = agent.get_action(state)
        total_action_epi.append(action)

        # 선택한 행동에 따라 다음 상태, 보상 및 종료 여부 얻기
        next_state, reward, done = env.step(action)
        score += reward
        agent.append_sample(state, action, next_state, reward, done)

        # 메모리가 충분히 쌓인 후 훈련 시작
        if len(agent.memory) > MEMORY_SIZE_MIN:
            agent.train_model()
            if done:
                agent.lr_scheduler.step()

        # 다음 상태를 현재 상태로 업데이트
        state = next_state

        # 종료 조건 처리
        if done:
            win_list.append(1 if reward == 1 else 0)

            # 주기적으로 타깃 모델 업데이트
            if (epi % UPDATE_TIME) == 0:
                agent.update_target_model()

            # 에피소드 결과 저장
            total_action.append(len(total_action_epi))
            episodes.append(epi)
            scores.append(score)
            score_avg.append(np.mean(scores[-100:]))
            length_memory.append(len(agent.memory))

            # 100번째 에피소드마다 진행상황 출력
            if (epi % 100) == 0:
                win_rate = np.mean(win_list[-100:]) if len(win_list) >= 100 else np.mean(win_list)
                loss_avg = np.mean(agent.loss_list[-100:]) if len(agent.loss_list) >= 100 else np.mean(agent.loss_list)
                action_avg = np.mean(total_action[-100:]) if len(total_action) >= 100 else np.mean(total_action)
                print(f"Episode: {epi} | Score: {np.median(scores[-100:]):.5f} | Epsilon: {agent.epsilon:.2f} | Win Rate: {win_rate}, Loss avg: {loss_avg:.5f} | Action avg: {action_avg}")


Episode: 0 | Score: -2.10000 | Epsilon: 1.00 | Win Rate: 0.0, Loss avg: nan | Action avg: 6.0
Episode: 100 | Score: -0.70000 | Epsilon: 0.10 | Win Rate: 0.02, Loss avg: 0.00543 | Action avg: 7.5
Episode: 200 | Score: -0.70000 | Epsilon: 0.10 | Win Rate: 0.01, Loss avg: 0.00603 | Action avg: 8.71
Episode: 300 | Score: -0.40000 | Epsilon: 0.10 | Win Rate: 0.01, Loss avg: 0.00617 | Action avg: 8.36
Episode: 400 | Score: -0.40000 | Epsilon: 0.10 | Win Rate: 0.01, Loss avg: 0.00882 | Action avg: 6.7
Episode: 500 | Score: -0.40000 | Epsilon: 0.10 | Win Rate: 0.03, Loss avg: 0.00814 | Action avg: 7.16
Episode: 600 | Score: -0.40000 | Epsilon: 0.10 | Win Rate: 0.0, Loss avg: 0.01243 | Action avg: 6.3
Episode: 700 | Score: -0.40000 | Epsilon: 0.10 | Win Rate: 0.0, Loss avg: 0.01147 | Action avg: 6.03
Episode: 800 | Score: -0.40000 | Epsilon: 0.10 | Win Rate: 0.02, Loss avg: 0.01287 | Action avg: 5.35
Episode: 900 | Score: -0.40000 | Epsilon: 0.10 | Win Rate: 0.02, Loss avg: 0.01120 | Action avg

## DDQN Main

In [18]:

env = MinesweeperEnv(map_size=(5,5),
                     n_mines=5,
                     rewards={'win': 1, 'lose': -1, 'progress': 0.3, 'guess': 0.3, 'no_progress': -1},
                     dones={'win': True, 'lose': True, 'progress': False, 'guess': False, 'no_progress': False},
                     dim2=False)

# 에이전트 초기화
agent = Agent(action_size=25)

# 학습 설정
EPISODES = 2000
episodes, scores, score_avg, total_action, length_memory, win_list = [], [], [], [], [], []

for epi in range(EPISODES):
    done = False
    score = 0
    total_action_epi = []

    # 게임 초기화
    env.reset()
    state = env.state

    while not done:
        # 현재 상태에 대한 행동 선택
        action = agent.get_action(state)
        total_action_epi.append(action)

        # 선택한 행동에 따라 다음 상태, 보상 및 종료 여부 얻기
        next_state, reward, done = env.step(action)
        score += reward
        agent.append_sample(state, action, next_state, reward, done)

        # 메모리가 충분히 쌓인 후 훈련 시작
        if len(agent.memory) > MEMORY_SIZE_MIN:
            agent.train_model()
            if done:
                agent.lr_scheduler.step()

        # 다음 상태를 현재 상태로 업데이트
        state = next_state

        # 종료 조건 처리
        if done:
            win_list.append(1 if reward == 1 else 0)

            # 주기적으로 타깃 모델 업데이트
            if (epi % UPDATE_TIME) == 0:
                agent.update_target_model()

            # 에피소드 결과 저장
            total_action.append(len(total_action_epi))
            episodes.append(epi)
            scores.append(score)
            score_avg.append(np.mean(scores[-100:]))
            length_memory.append(len(agent.memory))

            # 100번째 에피소드마다 진행상황 출력
            if (epi % 100) == 0:
                win_rate = np.mean(win_list[-100:]) if len(win_list) >= 100 else np.mean(win_list)
                loss_avg = np.mean(agent.loss_list[-100:]) if len(agent.loss_list) >= 100 else np.mean(agent.loss_list)
                action_avg = np.mean(total_action[-100:]) if len(total_action) >= 100 else np.mean(total_action)
                print(f"Episode: {epi} | Score: {np.median(scores[-100:]):.5f} | Epsilon: {agent.epsilon:.2f} | Win Rate: {win_rate}, Loss avg: {loss_avg:.5f} | Action avg: {action_avg}")


Episode: 0 | Score: -4.10000 | Epsilon: 0.99 | Win Rate: 0.0, Loss avg: nan | Action avg: 8.0
Episode: 100 | Score: -0.70000 | Epsilon: 0.58 | Win Rate: 0.02, Loss avg: 0.00485 | Action avg: 6.32
Episode: 200 | Score: -0.70000 | Epsilon: 0.27 | Win Rate: 0.01, Loss avg: 0.00460 | Action avg: 7.73
Episode: 300 | Score: -0.40000 | Epsilon: 0.14 | Win Rate: 0.01, Loss avg: 0.00430 | Action avg: 6.42
Episode: 400 | Score: -0.40000 | Epsilon: 0.08 | Win Rate: 0.01, Loss avg: 0.00468 | Action avg: 5.68
Episode: 500 | Score: -0.40000 | Epsilon: 0.04 | Win Rate: 0.01, Loss avg: 0.00459 | Action avg: 7.26
Episode: 600 | Score: -0.40000 | Epsilon: 0.02 | Win Rate: 0.02, Loss avg: 0.00469 | Action avg: 5.9
Episode: 700 | Score: -0.10000 | Epsilon: 0.01 | Win Rate: 0.05, Loss avg: 0.00403 | Action avg: 9.12
Episode: 800 | Score: -0.40000 | Epsilon: 0.01 | Win Rate: 0.02, Loss avg: 0.00366 | Action avg: 10.53
Episode: 900 | Score: -0.10000 | Epsilon: 0.01 | Win Rate: 0.03, Loss avg: 0.00378 | Actio

## 주니어

1. 레버 환경 만들기  
2. 카트폴 예제 -- 속도 개선, 학습 가능하게 만들기  
3. 매직 넘버 줄이기
4. 중간 중간 디버깅하면서 가기(구현 단위 별로 테스트)

### 1. 레버 환경 만들기

3개의 레버가 있다.  
- 1번 레버를 당겼을 때 바나나가 떨어질 확률이 0.7, 아무 것도 떨어지지 않을 확률이 0.3  
- 2번 레버를 당겼을 때 바나나가 떨어질 확률이 0.1, 상한 바나나 껍질만 떨어질 확률이 0.8, 아무 것도 떨어지지 않을 확률이 0.1  
- 3번 레버를 당겼을 때 상한 바나나 껍질만 떨어질 확률이 0.5, 아무 것도 떨어지지 않을 확률이 0.5  



1. 상태를 표현하는 방법   
2. 보상 구조 설계  
3. 한 번 행동 한 후 초기화하는 걸 전제    
4. 환경 로직 설계

In [ ]:
class LeverEnv:
    def __init__(self, **):
        pass

    def step(self, action):
        pass

    def reset(self):
        pass

    def render(self):
        pass

## 과제
1. 완성해오기(설명가능한 상태로 ipynb 파일 구성)    
2. 알파제로 구조 공부해오기(전원)  
3. 자기 코드 규칙 정리해오기